# Generated by Django 3.1.7 on 2024-02-17 22:17

from django.db import migrations, models


def change_first_login(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    PasswordRecord = apps.get_model("django_better_passwords", "PasswordRecord")
    PasswordRecord.objects.update(first_login=False)


class Migration(migrations.Migration):

    dependencies = [
        ('django_better_passwords', '0005_auto_20240217_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecord',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(change_first_login)
    ]
